# **Lab 0 - PCC177/BCC406**

## **REDES NEURAIS E APRENDIZAGEM EM PROFUNDIDADE**

### Profs. Eduardo e Pedro

Data da entrega : 12/08 

- Complete o código (marcado com ToDo) e escreva os textos diretamente nos notebooks.
- Execute todo notebook e salve tudo em um PDF nomeado como "NomeSobrenome-Lab0.pdf"
- Envie o PDF para via [Google FORM](https://forms.gle/n17SEBB3XJrawM96A).

Configure seu ambiente, seguindo os passos da seção de instalação do [livro](https://d2l.ai/chapter_installation/index.html) ou instale a distribuição [Anaconda](https://docs.anaconda.com/anaconda/install/). 

Se preferir usar Google CoLab, lembre-se de atualizar o drive do compilador CUDA da NVIDIA para que ele funcione com o MXNet. Veja exemplo no [link](https://colab.research.google.com/drive/16jvmGDx7Z51CSyDnRe9bbgtlWJWHA057?usp=sharing)

**Antes de realizar o notebook, leia a seção 2.1 do livro [texto](http://d2l.ai/chapter_preliminaries/ndarray.html).

# **NumPy**

*NumPy é uma das bibliotecas mais populares para computação científica. Ela foi desenvolvida para dar suporte a operações com arrays de N dimensões e implementa métodos úteis para operações de álgebra linear, geração de números aleatórios, etc.*

# Criando arrays

In [ ]:
# primeiramente, vamos importar a biblioteca
import numpy as np

In [ ]:
# usaremos a função zeros para criar um array de uma dimensão de tamanho 5
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# da mesma forma, para criar um array de duas dimensões:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## vocabulário comum

* Em NumPy, cada dimensão é chamada eixo (**axis**).
* Um array é uma lista de axis e uma lista de tamanho dos axis é o que chamamos de **shape** do array.
    * Por exemplo, o shape da matrix acima é `(3, 4)`.
    
* O tamanho (**size**) de uma array é o número total de elementos, por exemplo, no array 2D acima = 3*4=12.

In [ ]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a.ndim

2

In [ ]:
a.size

12

In [ ]:
# ToDo : Criar um array de 3 dimensões, de shape (2,3,4) e repetir as operações acima

In [ ]:
# ToDo : repita as operações acima trocando a função zeros por : ones, full, empty

## np.arange

você pode criar um array usando a função arange, similar a função range do Python.

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
# para criar com ponto flutuante
np.arange(1.0, 5.0)

array([1., 2., 3., 4.])

In [ ]:
# ToDo : crie um array com arange, variando de 1 a 5, com um passo de 0.5

## `np.rand` and `np.randn`
O NumPy tem várias funções para criação de números aleatórios. Estas funções são muito úteis para inicialização dos pesos das redes neurais. Por exemplo, abaixo criamos uma matrix 3,4 inicializada com números em ponto flutuante (floats) e distribuição uniforme:

In [ ]:
np.random.rand(3,4)

Abaixo um matriz inicializada com distribuição gaussiana ([normal distribution](https://en.wikipedia.org/wiki/Normal_distribution)) com média 0 e variância 1

In [ ]:
np.random.randn(3,4)

**ToDo** : Vamos usar a biblioteca matplotlib (para mais detalhes veja [matplotlib tutorial](https://drive.google.com/file/d/1f3Y_gm-URBVov5wIOs-JrdNw0gK86EXL/view?usp=sharing)) para plotar dois arrays de tamanho 10000, um inicializado com distribuição normal e o outro com uniforme

In [ ]:
%matplotlib inline
import matplotlib.pyplot as plt

In [ ]:
array_a = # ToDo : complete
array_b = # ToDo : complete

In [ ]:
plt.hist(array_a, density=True, bins=100, histtype="step", color="blue", label="rand")
plt.hist(array_b, density=True, bins=100, histtype="step", color="red", label="randn")
plt.axis([-2.5, 2.5, 0, 1.1])
plt.legend(loc = "upper left")
plt.title("Distribuições aleatṍrias")
plt.xlabel("Valor")
plt.ylabel("Densidade")
plt.show()

# Tipo de dados 
## `dtype`
Você pode ver qual o tipo de dado pelo atributo `dtype`. Verifique abaixo:

In [ ]:
c = np.arange(1, 5)
print(c.dtype, c)

In [ ]:
c = np.arange(1.0, 5.0)
print(c.dtype, c)

Tipos disponĩveis: `int8`, `int16`, `int32`, `int64`, `uint8`|`16`|`32`|`64`, `float16`|`32`|`64` e `complex64`|`128`. Veja a [documentação](http://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html) para a lista completa.

## `itemsize`
O atributo `itemsize` retorna o tamanho em bytes

In [ ]:
e = np.arange(1, 5, dtype=np.complex64)
e.itemsize

In [ ]:
# na memória, um array ẽ armazenado de forma contígua
f = np.array([[1,2],[1000, 2000]], dtype=np.int32)
f.data

# Reshaping 

Alterar o shape de uma array é muto fácil com NumPy e muito útil para adequação das matrizes para métodos de machine learning. Contudo, o tamanho (size) não pode ser alterado.

In [ ]:
# o núemro de dimensões também é chamado de rank
g = np.arange(24)
print(g)
print("Rank:", g.ndim)

In [ ]:
g.shape = (6, 4)
print(g)
print("Rank:", g.ndim)

In [ ]:
g.shape = (2, 3, 4)
print(g)
print("Rank:", g.ndim)

reshape

In [ ]:
g2 = g.reshape(4,6)
print(g2)
print("Rank:", g2.ndim)

In [ ]:
# Pode-se alterar diretamente um item da matriz, pelo índice
g2[1, 2] = 999
g2

In [ ]:
g

In [ ]:
#repare que o objeto 'g' foi modificado também!

Todas a operçãoes aritméticas comuns podem ser feitas com o ndarray

In [ ]:
a = np.array([14, 23, 32, 41])
b = np.array([5,  4,  3,  2])
print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a // b  =", a // b)
print("a % b  =", a % b)
print("a ** b =", a ** b)

Repare que a multiplicação acima NÃO é um multiplicação de martizes

Arrays devem ter o mesmo shape, caso contrário, NumPy vai aplicar a regra de *broadcasting* (Ver seção 2.1.3 do [livro texto](http://d2l.ai/chapter_preliminaries/ndarray.html)). Pesquise sobre a operação ed bradcasting do NumPy e explique com suas palavras, abaixo:

**ToDo** : Explique aqui o conceito de broadcasting

# Iterando : repare que você pode iterar pelos ndarrays. Repare que a iteração é feita pelos axis.

In [ ]:
c = np.arange(24).reshape(2, 3, 4)  # A 3D array (composed of two 3x4 matrices)
c

In [ ]:
for m in c:
    print("Item:")
    print(m)

In [ ]:
for i in range(len(c)):  # Note that len(c) == c.shape[0]
    print("Item:")
    print(c[i])

In [ ]:
# para iteirar por todos os elementos
for i in c.flat:
    print("Item:", i)

# Concatenando arrays

In [ ]:
# pode-se concatenar arrays pelos axis
q1 = np.full((3,4), 1.0)

q2 = np.full((4,4), 2.0)

q3 = np.full((3,4), 3.0)

q = np.concatenate((q1, q2, q3), axis=0)  
q

# Transposta


In [ ]:
m1 = np.arange(10).reshape(2,5)
m1

In [ ]:
# ToDo : imprima a matriz transposta de m1

# Produto de matrizes

In [ ]:
n1 = np.arange(10).reshape(2, 5)
n1

In [ ]:
n2 = np.arange(15).reshape(5,3)
n2

In [ ]:
n1.dot(n2)

# Matriz Inversa

In [ ]:
import numpy.linalg as linalg

m3 = np.array([[1,2,3],[5,7,11],[21,29,31]])
m3

In [ ]:
linalg.inv(m3)

# Matriz identidade

In [ ]:
m3.dot(linalg.inv(m3))

# Comparando os objetos de array

Os objetos do tipo array das bibliotecas de deep learning (tensorflow, pytorch, mxnet) são muito parecedios com o do NumPy. Porém, otimizados. Crie um objeto do tipo NDArray do MXNet e compare a performance contra o objeto do NumPy.

In [ ]:
!pip install -U mxnet-cu101==1.7.0
from mxnet import nd, gpu, gluon, autograd
import mxnet as mx
from mxnet.gluon import nn
import time

     |███████████████████████████████▌| 834.1MB 1.1MB/s eta 0:00:11tcmalloc: large alloc 1147494400 bytes == 0x564548232000 @  0x7f64e7861615 0x56450e87006c 0x56450e94feba 0x56450e872e8d 0x56450e96499d 0x56450e8e6fe9 0x56450e8e1b0e 0x56450e87477a 0x56450e8e6e50 0x56450e8e1b0e 0x56450e87477a 0x56450e8e386a 0x56450e9657c6 0x56450e8e2ee2 0x56450e9657c6 0x56450e8e2ee2 0x56450e9657c6 0x56450e8e2ee2 0x56450e9657c6 0x56450e8e2ee2 0x56450e87469a 0x56450e8e2c9e 0x56450e8e1e0d 0x56450e87477a 0x56450e8e2a45 0x56450e87469a 0x56450e8e2a45 0x56450e8e1b0e 0x56450e87477a 0x56450e8e386a 0x56450e8e1b0e
     |████████████████████████████████| 846.0MB 21kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [ ]:
#criando um array com ndarray do mxnet
nd.array(( (1,2,3), (4,5,6) ))

In [ ]:
# crianod-se uma matriz 
x = nd.ones(shape = (2,3))
x

O objeto NDArray do MXNet também possui as funções de criação de números aleatórios e de algebra, feito as do NumPy.

In [ ]:
#criando uma matrix uniforme aleatoria, com valores entre -1 e 1
y = nd.random.uniform(low=-1, high=1, shape = (2,3))
y

Diferentemente do numpy, NDArray me permite colocar os dados em alguma CPU especĩfica ou em alguma GPU : repare no contexto!

In [ ]:
# shape e tamanho da matriz
# os outros parâmetros são o tipo de dados e contexto

(x.shape, x.size, x.dtype, x.context)

In [ ]:
# pode-se definir o tipo de dados em tempo de criação 
nd.ones(shape = (2,3), dtype = np.uint8)

In [ ]:
# ou pode-se alterar dinamicamente
y.astype(np.float16)

Alocando na CPU

In [ ]:
#NDArray permite alocar me CPU e GPU
nd.ones(shape = (2,3), ctx=mx.cpu())

Alocando na GPU

In [ ]:
nd.ones(shape = (2,3), ctx=mx.gpu())

**ToDo**:

Crie 6 matrizes, com a função ones:

- Uma de shape (10000, 5000) e outra com shape (5000, 10000), usando-se o objeto do NumPy.
- Uma de shape (10000, 5000) e outra com shape (5000, 10000), usando-se o objeto do NDArray do MXNets, porém alocada em CPU.
- Uma de shape (10000, 5000) e outra com shape (5000, 10000), usando-se o objeto do NDArray do MXNets, porém alocada em GPU.

In [ ]:
x_np, y_np = # ToDo : complete

x_nd_cpu , y_nd_cpu = # ToDo : complete

x_nd_gpu , y_nd_gpu = # ToDo : complete

Execute as multiplicações e verifique o tempo de execução

In [ ]:
tic = time.time()
np.dot(x_np, y_np)
print("NumPy time : {:.4f}s".format(time.time()-tic))

In [ ]:
tic = time.time()
nd.dot(x_nd_cpu, y_nd_cpu)
print("MXNet CPU time : {:.4f}s".format(time.time()-tic))

In [ ]:
tic = time.time()
nd.dot(x_nd_gpu, y_nd_gpu)
print("MXNet GPU time : {:.4f}s".format(time.time()-tic))